### ISSUE TITLE
rabbit_auth_backend_oauth2 instead of rabbitmq_auth_backend_oauth2

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [rabbitmq/rabbitmq-oauth2-tutorial#16]
https://github.com/rabbitmq/rabbitmq-oauth2-tutorial/blob/922f2d6d546030961e146c6609f920ff80398e21/README.md?plain=1#L692

Is there any reason why there is no ```rabbitmq```, but ```rabbit``` module name?

**Comment by MarcialRosales** [comment]
There is no reason. It has been like that since the beginning.
