### ISSUE TITLE
rabbitmq.config missing in Keycloak tutorial

### ISSUE THREAD

**Issue by alexandernajafi** [rabbitmq/rabbitmq-oauth2-tutorial#18]
In the Keycloak tutorial there is a link to the file [rabbitmq.config](https://github.com/rabbitmq/rabbitmq-oauth2-tutorial/blob/main/use-cases/conf/keycloak/rabbitmq.config) but it is broken. It would be great to add the file.

**Comment by MarcialRosales** [comment]
It is now fixed @alexandernajafi . Thanks for reporting it .
