### ISSUE TITLE
Keycloak example not working (with rabbitmq.conf version)

### ISSUE THREAD

**Issue by Schmitze333** [rabbitmq/rabbitmq-oauth2-tutorial#24]
### Describe the bug

When following the instructions from the readme with regard to the `keycloak` example, one is unable to authorise to RabbitMQ.

### Reproduction steps

Follow the [readme for the keycloak use-case](https://github.com/rabbitmq/rabbitmq-oauth2-tutorial/blob/main/use-cases/keycloak.md):
1. run `make start-keycloak`
2. run `export MODE=keycloak`
3. run `make start-rabbitmq`

Accessing RabbitMQ is not possible due to `Not Authorized`.

### Expected behavior

The given configurations should reflect a working state.

### Additional context

After some research we found out that:
- The rabbitmq.conf was referencing the key with the internal keycloak ID instead of the `kid`.
- The signing-key referenced by the rabbitmq.conf was wrong.

A PR will follow to address this.

**Comment by MarcialRosales** [comment]
Resolved by https://github.com/rabbitmq/rabbitmq-oauth2-tutorial/pull/25
