### ISSUE TITLE
http://localhost:15672/#/login//<token> not working anymore

### ISSUE THREAD

**Issue by CasperTDK** [rabbitmq/rabbitmq-oauth2-tutorial#4]
There is no audit logs in rabbitmq and the console writes:

```log
Jan 05 2022 09:40:58 GMT+0100 (Central European Standard Time)] body 404 Not Found get /#/login//eyJhbGci[xxxx]
    at Sammy.Application.error (sammy-0.7.6.min.js:5)
    at Sammy.Application.notFound (sammy-0.7.6.min.js:5)
    at Sammy.Application.runRoute (sammy-0.7.6.min.js:5)
    at Sammy.Application._checkLocation (sammy-0.7.6.min.js:5)
    at Sammy.Application.run (sammy-0.7.6.min.js:5)
    at start_app_login (main.js:76)
    at HTMLDocument.<anonymous> (main.js:13)
    at e (jquery-3.5.1.min.js:2)
    at t (jquery-3.5.1.min.js:2)
```

I suspect a breaking change in the sammy js framework, but I can not find any sourcecode that handles `/#/login//` in previous versions of rabbitmq either. Do you have any insights to share @MarcialRosales  ?

**Comment by MarcialRosales** [comment]
Sorry @CasperTDK for this unacceptable late response. I apologise. It is definitely broken. I have updated the section in the tutorial to get around it. It turns out that now we have to send the token in the request parameter `access_token` rather than putting directly onto the URI.

**Comment by cthtrifork** [comment]
Thanks for investigating!

**Comment by MarcialRosales** [comment]
@CasperTDK @cthtrifork This issue has been addressed in this [PR](https://github.com/rabbitmq/rabbitmq-server/pull/6015). It has not been released yet. The request is `/#/login?access_token=<jwt>`. 
Should you wanted to test it, there is a dev docker image: `pivotalrabbitmq/rabbitmq:oidc_idp_initiated_login-otp-max-bazel `

**Comment by MarcialRosales** [comment]
Hi @CasperTDK This feature is readily available in the current version of this repo which uses RabbitMQ 3.11.7 and it is covered on this [section](https://github.com/rabbitmq/rabbitmq-oauth2-tutorial#identity-provider-initiated-logon) of the docs. I am closing now the issue.
