### ISSUE TITLE
Build and publish images used in examples

### ISSUE THREAD

**Issue by MirahImage** [rabbitmq/rabbitmq-oauth2-tutorial#6]
Rather than requiring users of the guide to build their own images, it would be helpful to build and publish the images used throughout the guide.

**Comment by MirahImage** [comment]
In the case of the UAA image, for example, we could simply make use of the UAA image provided by the UAA team: `cloudfoundry/uaa:latest`

**Comment by MarcialRosales** [comment]
@MirahImage definitely ! that is the way to go . When I first started this tutorial I had issues using the latest docker image that is why I chose to build an image from a commit that worked. But now, everything works fine using the latest docker image from UAA.

**Comment by MirahImage** [comment]
Closed by #7
